name: "build"
on:
  push:
    paths-ignore:
      - "**.md"
      - "locale/**"
      - ".github/**"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "**.md"
      - "locale/**"
      - ".github/**"
    branches:
      - master
  workflow_dispatch:

jobs:
  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Installo Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Installo Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: src-tauri/
      - name: Installo le librerie
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Installo le dipendenze
        run: yarn
      - name: Compilo il programma
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compilo il programma per debug
        if: matrix.platform == 'windows-latest'
        run: yarn tauri build --debug
      - name: Carico il risultato
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "artifacts-${{ matrix.platform }}"
          path: "src-tauri/target/release/bundle/"
          if-no-files-found: error
      - name: Carico il risultato di debug
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "artifacts-${{ matrix.platform }}-debug"
          path: "src-tauri/target/debug/bundle/"
          if-no-files-found: error
